### ISSUE TITLE
update Cocoapods to fix swift 3.0

### ISSUE THREAD

**Issue by 5SMNOONMS5** [yourtion/HTTPDNS-Swift#2]
因為目前專案是 swift 3.1 ，想請問有考慮要升級專案 swift 版本嗎 ？

**Comment by yourtion** [comment]
使用Swift 3.0 会有问题？现在Swift Language Version 是 3 哦

**Comment by 5SMNOONMS5** [comment]
這是我安裝遇到的錯誤

![screen shot 2017-09-08 at 9 52 05 pm 2](https://user-images.githubusercontent.com/8379901/30215234-ecaa7dc2-94e1-11e7-8fc3-ccc7219d79ef.png)

Cat log
![screen shot 2017-09-08 at 9 53 19 pm 2](https://user-images.githubusercontent.com/8379901/30215253-fff4c3ce-94e1-11e7-9e7f-d9b0b948efb5.png)

我也確認過我的專案版本了

![screen shot 2017-09-08 at 10 00 09 pm 2](https://user-images.githubusercontent.com/8379901/30215266-0ec69f4e-94e2-11e7-85b0-0b49518b394d.png)

**Comment by yourtion** [comment]
找到问题了，应该是我之前更新后忘记打tag了，现在已经修复，更新了 0.8.0

![image](https://user-images.githubusercontent.com/1475301/30216242-f53be7fc-94e4-11e7-92cf-66d528152f4d.png)

**Comment by 5SMNOONMS5** [comment]
![screen shot 2017-09-08 at 10 44 10 pm 2](https://user-images.githubusercontent.com/8379901/30216946-411db298-94e7-11e7-9c50-f1eb670361bf.png)
我剛剛才 pod install 一下發現應該是沒有更新到 cocoapods，總之感謝

**Comment by yourtion** [comment]
pod的版本我还在发布更新。carthage的是因为我的tag打得有问题。

感谢你才是，帮我发现问题，使用过程还有什么意见建议欢迎反馈

**Comment by 5SMNOONMS5** [comment]
嘿嘿 好 這週末來細看研究看看：）

**Comment by yourtion** [comment]
这个库也写了有些时间，等待更新Swift 4.0
